{{- if not (lookup "rbac.authorization.k8s.io/v1" "Role" .Release.Namespace "harness-namespace-admin") }}
{{- if eq .Values.k8sPermissionsType "NAMESPACE_ADMIN" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: harness-namespace-admin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harness-delegate-ng.labels" . | nindent 4 }}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
{{- end }}
{{- end }}