{{- if .Values.upgrader.enabled -}}
{{- if not (lookup "rbac.authorization.k8s.io/v1" "Role" .Release.Namespace "upgrader-role" ) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: upgrader-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harness-delegate-ng.labels" . | nindent 4 }}
rules:
  - apiGroups: ["batch", "apps", "extensions"]
    resources: ["cronjobs"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["extensions", "apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
{{- end }}
{{- end }}